Repository framgia/sph-classroom-els-be, pull requests merged in 2021-11, with the labels that each got.

#5 E_CLASSROOM-130 [API] [Database] Application Models and Relationships
  .env.example
  app/Models/Activity.php
  app/Models/Category.php
  app/Models/Choice.php
  app/Models/Following.php
  app/Models/Question.php
  app/Models/QuestionType.php
  app/Models/Quiz.php
  app/Models/User.php
  app/Models/UserType.php
  database/migrations/2021_10_31_111331_add_constrain_on_users_table.php
  database/migrations/2021_10_31_111427_add_constrain_on_categories_table.php
  database/migrations/2021_10_31_115613_add_softdeletes_on_user_types_table.php
  database/migrations/2021_10_31_115856_add_softdeletes_on_question_types_table.php
  database/migrations/2021_10_31_120121_add_constrain_on_activities_table.php
  database/migrations/2021_10_31_120511_add_constrain_on_following_table.php
  database/migrations/2021_10_31_120940_add_constrain_on_quizzes_table.php
  database/migrations/2021_10_31_122201_drop_status_on_quizzes_table.php
  database/migrations/2021_10_31_122524_add_constrain_on_questions_table.php
  database/migrations/2021_10_31_123034_add_constrain_on_choices_table.php
  database/seeders/ChoiceSeeder.php
  database/seeders/QuizSeeder.php
Labels: Approved by Geneno, High Priority

#6 E_CLASSROOM-101 [API] [Seeders] User Types
  database/seeders/DatabaseSeeder.php
  database/seeders/UserTypeSeeder.php
Labels: Approved by Erron, Approved by Geneno

#4 feature/E-CLASSROOM-109-API-user-profile-functionality
  app/Http/Controllers/API/v1/User/UserController.php
  app/Http/Controllers/Controller.php
  app/Http/Requests/User/UpdateUserRequest.php
  app/Models/Activity.php
  app/Models/Category.php
  app/Models/Choice.php
  app/Models/Following.php
  app/Models/Question.php
  app/Models/QuestionType.php
  app/Models/Quiz.php
  app/Models/User.php
  app/Models/UserType.php
  app/Traits/ResponseMessage.php
  routes/api.php
Labels: Erron is Reviewing, Approved by Geneno

#7 Feature/e classroom 108 api categories crud operations
  app/Http/Controllers/API/v1/Category/CategoryController.php
  app/Http/Requests/Category/StoreCategoryRequest.php
  app/Http/Requests/Category/UpdateCategoryRequest.php
  app/Models/Category.php
  routes/api.php
Labels: Approved by Erron, Approved by Geneno

#10 E_CLASSROOM-106 [Backend] [API] User Authentication 1/2 and E_CLASSRO…
  app/Http/Controllers/API/v1/Auth/AuthController.php
  app/Http/Controllers/API/v1/User/UserController.php
  app/Http/Kernel.php
  app/Http/Requests/Auth/LoginRequest.php
  app/Http/Requests/Auth/RegisterRequest.php
  app/Models/User.php
  app/Traits/ResponseMessage.php
  composer.json
  composer.lock
  database/seeders/AdminSeeder.php
  database/seeders/DatabaseSeeder.php
  database/seeders/StudentSeeder.php
  routes/api.php
Labels: Erron is Reviewing, Approved by Geneno

#9 Feature/e classroom 112 api quiz questions list
  app/Http/Controllers/API/v1/Quiz/QuestionController.php
  app/Http/Controllers/API/v1/Quiz/QuizController.php
  app/Http/Controllers/Controller.php
  app/Models/Question.php
  app/Traits/ResponseMessage.php
  routes/api.php
Labels: Erron is Reviewing, Approved by Geneno

#12 E_CLASSROOM-132 [API] [Markup] [Setup] Quiz List Page
  app/Http/Controllers/API/v1/Quiz/QuizController.php
  app/Models/Quiz.php
  database/migrations/2021_11_08_053855_add_title_field_to_quizzes_table.php
  database/seeders/QuizSeeder.php
Labels: Approved by Erron

#11 E_CLASSROOM-114 [API] Password Reset
  app/Http/Controllers/API/v1/Auth/ForgotPasswordController.php
  app/Http/Requests/Auth/ForgotPasswordRequest.php
  app/Http/Requests/Auth/ResetRequest.php
  app/Models/User.php
  app/Notifications/ResetPasswordNotification.php
  routes/api.php
Labels: For QA Review, Approved by Erron, Mary Therese is Reviewing

#13 E_CLASSROOM-103 [Frontend] [Student] [Integration] User Authentication 1/2
  app/Http/Controllers/API/v1/Auth/AuthController.php
  app/Traits/ResponseMessage.php
  database/migrations/2021_10_27_075645_modify_users_table.php
  routes/api.php
Labels: Approved by Geneno

#14 E_CLASSROOM-118 [Integration] [Student] Password Reset
  app/Http/Controllers/API/v1/Auth/ForgotPasswordController.php
  app/Models/User.php
Labels: Approved by Erron

#15 E_CLASSROOM-136 [API] Quiz List Pagination
  app/Http/Controllers/API/v1/Quiz/QuizController.php
  app/Traits/Pagination.php
  app/Traits/ResponseMessage.php
  composer.lock
Labels: Approved by Erron, Approved by Lim

#17 E_CLASSROOM-135 [API] Category List Pagination
  app/Http/Controllers/API/v1/Category/CategoryController.php
Labels: Approved by Erron, Approved by Lim

#16 E_CLASSROOM-115 [API] Change Password
  app/Http/Controllers/API/v1/Auth/ChangePasswordController.php
  app/Http/Requests/ChangePassword/ChangePasswordRequest.php
  routes/api.php
Labels: Erron is Reviewing, Approved by Lim

#21 Feature/e classroom 121 integration student subcategories page backend
  app/Http/Controllers/API/v1/Category/CategoryController.php
  app/Models/Category.php
  database/seeders/DatabaseSeeder.php
  database/seeders/SubcategorySeeder.php
Labels: Approved by Erron, Approved by Geneno

#20 Routes and Controllers for Quizzes Taken
  app/Http/Controllers/API/v1/Quiz/QuizAnswerController.php
  app/Http/Controllers/API/v1/Quiz/QuizzesTakenController.php
  app/Http/Requests/Quiz/StoreQuizAnswerRequest.php
  app/Http/Requests/Quiz/StoreQuizTakenRequest.php
  app/Http/Requests/Quiz/UpdateQuizTakenRequest.php
  app/Models/Answer.php
  app/Models/Choice.php
  app/Models/Question.php
  app/Models/Quiz.php
  app/Models/User.php
  database/migrations/2021_11_17_031238_create_quizzes_taken_table.php
  database/migrations/2021_11_17_041301_create_answers_table.php
  routes/api.php
Labels: Approved by Erron, Approved by Lim

#19 [E_CLASSROOM-17][Setup] Set up Unit Test
  .env.test.example
  .sun-ci.yml
  phpunit.xml
Labels: Approved by Erron

#22 E_CLASSROOM-174 [BE] Student List Page Backend Functionality [1/3]
  app/Http/Controllers/API/v1/Student/StudentController.php
  routes/api.php
Labels: Approved by Erron, Approved by Lim

#23 feature/E_CLASSROOM-175-BE-Follow-Unfollow-Functionality
  app/Http/Controllers/API/v1/Follow/FollowController.php
  app/Http/Controllers/API/v1/Student/StudentController.php
  app/Models/User.php
  composer.json
  composer.lock
  config/app.php
  config/follow.php
  database/migrations/2020_04_04_000000_create_user_follower_table.php
  routes/api.php
Labels: Approved by Erron, Approved by Lim

#24 feature/E_CLASSROOM-176-BE-Get-Student-List-With-Filtering-Backend-Functionality
  app/Http/Controllers/API/v1/Student/StudentController.php
  app/Traits/StudentFilter.php
Labels: For Code Review, Approved by Lim

#25 E_CLASSROOM-182 [BE] Student Detail Page Backend Functionality [1/4]
  app/Http/Controllers/API/v1/Student/StudentController.php
  routes/api.php
Labels: Approved by Erron, Approved by Lim
