Repository framgia/sph-classroom-els-be, pull requests merged in 2021-12, with the labels that each got.

#26 E_CLASSROOM-195-[BE]-Student-List-Page-Search-Functionality
  app/Http/Controllers/API/v1/Student/StudentController.php
  app/Models/User.php
  app/Traits/StudentFilter.php
Labels: Approved by Erron, Approved by Lim

#27 E_CLASSROOM-187 [BE] Student Detail Page Backend Functionality [3/4]
  app/Http/Controllers/API/v1/Quiz/QuizzesTakenController.php
  routes/api.php
Labels: Approved by Erron, Approved by Lim

#29 E_CLASSROOM-167 [BE] Functionality for Categories Learned
  app/Http/Controllers/API/v1/Quiz/QuizzesTakenController.php
  routes/api.php
Labels: Erron is Reviewing, Approved by Geneno

#28 E_CLASSROOM-165 [BE] Functionality Recent Activity of Current User
  app/Http/Controllers/API/v1/Student/ActivityLogController.php
  app/Http/Controllers/API/v1/User/UserRecentQuizzesController.php
  app/Models/ActivityLogs.php
  config/activitylog.php
  database/migrations/2021_11_29_051810_create_activity_log_table.php
  database/migrations/2021_11_29_051811_add_event_column_to_activity_log_table.php
  database/migrations/2021_11_29_051812_add_batch_uuid_column_to_activity_log_table.php
  routes/api.php
Labels: Approved by Erron, Approved by Geneno

#30 Feature/e classroom 189 student improvement user authentication pages validation be
  app/Http/Controllers/API/v1/Auth/AuthController.php
  app/Http/Requests/Auth/LoginRequest.php
  app/Http/Requests/Auth/RegisterRequest.php
  app/Http/Requests/Auth/ResetRequest.php
Labels: Approved by Erron, Approved by Lim

#31 Modified the StudentController to include number of quizzes taken re…moved the following relationship from the User Model so that package works
  app/Http/Controllers/API/v1/Student/StudentController.php
  app/Models/User.php
Labels: For Code Review, Approved by Lim

#32 Feature/e classroom 188 be student detail page backend functionality 4/4
  app/Http/Controllers/API/v1/Follow/FollowController.php
  app/Http/Controllers/API/v1/Quiz/QuizzesTakenController.php
  app/Http/Controllers/API/v1/Student/ActivityLogController.php
  app/Http/Controllers/API/v1/Student/StudentActivitiesController.php
  app/Models/QuizTaken.php
  database/migrations/2021_12_06_062232_create_activity_log_table.php
  database/migrations/2021_12_06_062233_add_event_column_to_activity_log_table.php
  database/migrations/2021_12_06_062234_add_batch_uuid_column_to_activity_log_table.php
  routes/api.php
Labels: Approved by Erron, Approved by Lim

#33 [E_CLASSROOM-169][BE] Functionality for Friends Activities
  app/Http/Controllers/API/v1/Student/StudentActivitiesController.php
  routes/api.php
Labels: Approved by Royce, For Code Review, Approved by Lim

#34 E_CLASSROOM-198 [Bugfix] Dashboard error categoriesLearned
  app/Http/Controllers/API/v1/Quiz/QuizzesTakenController.php
  composer.json
  composer.lock
Labels: For Code Review, Approved by Lim

#36 E_CLASSROOM-166 [BE] [Student] Recent Activity Functionality with # of Attempts and Highest Score
  app/Http/Controllers/API/v1/User/UserRecentQuizzesController.php
Labels: Approved by Royce, For Code Review, Approved by Geneno

#35 E_CLASSROOM-192 [FE] [BE] [Student] [Improvement] Quiz Results Page F…
  app/Http/Controllers/API/v1/User/UserfriendsScoreController.php
  routes/api.php
Labels: Royce is reviewing, Approved by Geneno

#37 E_CLASSROOM-203 [Bugfix] Dashboard Recent Attempt Display Issue
  app/Http/Controllers/API/v1/User/UserRecentQuizzesController.php
Labels: Approved by Royce, Approved by Lim
