Repository framgia/sph-classroom-els-be, pull requests merged in 2022-01, with the labels that each got.

#43 E_CLASSROOM-209 BE Category Sort Function
  app/Http/Controllers/API/v1/Category/CategoryController.php
Labels: Approved by Royce, For Code Review, Approved by John Harvey

#42 E_CLASSROOM-210 [BE] Category Filter Function
  app/Http/Controllers/API/v1/Category/CategoryController.php
  app/Traits/CategoryFilter.php
Labels: For Code Review, Approved by John Harvey

#41 E_CLASSROOM-211 BE Category Search Function
  app/Http/Controllers/API/v1/Category/CategoryController.php
  app/Traits/CategoryFilter.php
Labels: Approved by Royce, For Code Review, Approved by John Harvey

#39 E_CLASSROOM-204 [FE/BE] Make Category Quizzes page dynamic
  app/Http/Controllers/API/v1/User/UserScoresAndAttemptsController.php
  routes/api.php
Labels: Approved by Royce, Approved by Lim

#38 E_CLASSROOM-193 [FE] [BE] [Student] [Improvement] Quiz Results Page R…
  app/Http/Controllers/API/v1/Quiz/QuizController.php
  routes/api.php
Labels: For Code Review, Approved by Lim

#44 E_CLASSROOM-215-FE/BE-Profile-Edit-Function - first commit
  app/Http/Controllers/API/v1/Auth/ChangeNameEmailController.php
  app/Http/Controllers/API/v1/User/UploadImageController.php
  app/Http/Requests/Auth/ChangeNameEmailRequest.php
  app/Http/Requests/Auth/UploadImageRequest.php
  routes/api.php
Labels: Approved by John Harvey, Karlo is Reviewing

#45 E_CLASSROOM-241 [Admin] BE Implement Admin Login
  app/Http/Controllers/API/v1/Auth/AuthController.php
  resources/lang/en/auth.php
Labels: Approved by John Harvey, Approved by Karlo
