Repository framgia/sph-classroom-els-be, pull requests merged in 2022-02, with the labels that each got.

#46 E_CLASSROOM-244 [FE/BE] Profile picture upload
  app/Http/Controllers/API/v1/Student/StudentController.php
  app/Http/Controllers/API/v1/User/UploadImageController.php
  app/Http/Kernel.php
  app/Http/Middleware/cors.php
  routes/api.php
Labels: Approved by Mary Therese, Approved by Karlo

#48 E_CLASSROOM-256 [Bugfix] [Student list] Avatar in the student list and friend's score section is not displaying properly
  app/Http/Controllers/API/v1/Student/StudentController.php
  app/Http/Controllers/API/v1/User/UserfriendsScoreController.php
  app/Traits/StudentAvatar.php
Labels: Approved by Joash, Karlo is Reviewing

#47 E_CLASSROOM-236 [Student][Learnings][FE/BE] Display all quizzes
  app/Http/Controllers/API/v1/Learn/LearningsController.php
  routes/api.php
Labels: Approved by John Harvey, Approved by Karlo

#49 E_CLASSROOM-249 [FE/BE] Display dynamic quizzes data
  app/Http/Controllers/API/v1/Quiz/QuizController.php
  routes/api.php
Labels: Approved by John Harvey, Karlo is Reviewing

#51 E_CLASSROOM-270 [Bugfix] Apply Red Color for Failed Scores and Apply Validation Error Messages for Dupilcate Emails
  app/Http/Controllers/API/v1/Auth/ChangeNameEmailController.php
  app/Http/Requests/Auth/ChangeNameEmailRequest.php
Labels: For QA Review, For Code Review

#54 E_CLASSROOM-258 [Admin] [FE/BE] Add/Edit categories functionality
  app/Http/Controllers/API/v1/Category/CategoryController.php
  app/Http/Requests/Category/StoreCategoryRequest.php
  app/Http/Requests/Category/UpdateCategoryRequest.php
  app/Models/Category.php
  routes/api.php
Labels: Approved by John Harvey, Approved by Karlo

#53 E_CLASSROOM-261 [FE/BE] Moving Subcategories Functionality
  app/Http/Controllers/API/v1/Category/CategoryController.php
  app/Http/Requests/Quiz/StoreQuizRequest.php
  routes/api.php
Labels: Approved by John Harvey, Approved by Karlo

#55 E_CLASSROOM-275 [Bugfix] Category name cannot be edited and description misleading error message
  app/Http/Requests/Category/StoreCategoryRequest.php
  app/Http/Requests/Category/UpdateCategoryRequest.php
Labels: Approved by John Harvey, Karlo is Reviewing

#52 E_CLASSROOM-254 [FE/BE] Implement adding a new question
  app/Http/Controllers/API/v1/Quiz/QuestionController.php
  app/Http/Requests/Choices/ChoiceRequest.php
  app/Http/Requests/Choices/EditChoiceRequest.php
  app/Http/Requests/Question/AddQuestionRequest.php
  app/Http/Requests/Question/EditQuestionRequest.php
  app/Models/Choice.php
  app/Models/Question.php
  routes/api.php
Labels: Approved by Paul Erick, Approved by Karlo

#56 E_CLASSROOM-277 [FE/BE] Implement subcategory functionality in category form
  app/Http/Controllers/API/v1/Category/CategoryController.php
  routes/api.php
Labels: Approved by Paul Erick, Karlo is Reviewing
