Repository framgia/sph-classroom-els-be, pull requests merged in 2022-03, with the labels that each got.

#57 E_CLASSROOM-282 [FE/BE] Invite Admin User
  app/Http/Controllers/API/v1/Admin/AdminController.php
  app/Http/Requests/Admin/StoreAdminRequest.php
  app/Notifications/InvitationToJoinAsAdmin.php
  config/app.php
  resources/lang/en/auth.php
  routes/api.php
Labels: Approved by John Harvey, Approved by Karlo

#58 E_CLASSROOM-283[FE/BE] Admin Invitation Acceptance
  app/Http/Controllers/API/v1/Admin/AdminController.php
  app/Http/Requests/Admin/SetAdminPasswordRequest.php
  routes/api.php
Labels: Approved by John Harvey, Approved by Karlo

#60 E_CLASSROOM-284 [FE/BE] Update Account Info
  app/Http/Controllers/API/v1/Auth/ChangeNameEmailController.php
  app/Http/Requests/Admin/UpdateNameEmailRequest.php
  routes/api.php
Labels: Approved by John Harvey, Approved by Karlo

#62 E_CLASSROOM-300 [Bugfix] Password field should not update password
  app/Http/Controllers/API/v1/Auth/ChangeNameEmailController.php
  app/Http/Requests/Admin/UpdateNameEmailRequest.php
Labels: Approved by Mary Therese, Approved by Karlo

#61 E_CLASSROOM-288 (Dependent #296) [FE/BE] Quizzes Sort by Column
  app/Http/Controllers/API/v1/Quiz/QuizController.php
  app/Traits/QuizSort.php
Labels: Approved by John Harvey, Approved by Karlo

#63 E_CLASSROOM-299 [FE/BE] [Admin] Change Password Page
  app/Http/Controllers/API/v1/Admin/AdminController.php
  app/Http/Requests/Admin/UpdatePasswordRequest.php
  routes/api.php
Labels: Approved by John Harvey, Approved by Karlo

#65 E_CLASSROOM-297 [Bugfix] Edit Category can have an identical title
  app/Http/Requests/Category/UpdateCategoryRequest.php
Labels: John Harvey is Reviewing, Approved by Karlo

#66 E_CLASSROOM-276 [FE/BE] Accounts List Page
  app/Http/Controllers/API/v1/Admin/AdminController.php
  database/seeders/AdminSeeder.php
  routes/api.php
Labels: Approved by Paul Erick, Karlo is Reviewing

#67 E_CLASSROOM-286 (Dependent #288) [FE/BE] Categories sort by column
  app/Http/Controllers/API/v1/Category/CategoryController.php
  app/Traits/SortCategories.php
  routes/api.php
Labels: Approved by Mary Therese, Karlo is Reviewing

#68 E_CLASSROOM-298 [FE/BE] [Admin] Profile Account Page
  app/Http/Controllers/API/v1/User/UserController.php
Labels: Approved by John Harvey, Approved by Karlo

#69 E_CLASSROOM-295 [Admin] [FE/BE] Admin User search by name or email
  app/Http/Controllers/API/v1/Admin/AdminController.php
  app/Models/User.php
Labels: Approved by John Harvey, Karlo is Reviewing

#70 E_CLASSROOM-280 [FE/BE] Sort admin table by column
  app/Http/Controllers/API/v1/Admin/AdminController.php
Labels: Approved by John Harvey, Approved by Karlo

#71 E_CLASSROOM-301 [FE/BE] [Admin] Filtering quizzes by name and category
  app/Http/Controllers/API/v1/Category/CategoryController.php
  app/Http/Controllers/API/v1/Quiz/QuizController.php
Labels: Approved by John Harvey, Karlo is Reviewing

#74 E_CLASSROOM-293 [Admin] [FE/BE] Categories search by name
  app/Http/Controllers/API/v1/Category/CategoryController.php
Labels: Approved by John Harvey, Karlo is Reviewing

#73 E_CLASSROOM-279 [FE/BE] Implement the add/edit of a question
  app/Http/Controllers/API/v1/Quiz/QuestionController.php
Labels: Approved by John Harvey, Approved by Karlo

#75 E_CLASSROOM-314 [FE/BE] Implement Delete a Question
  app/Http/Controllers/API/v1/Category/CategoryController.php
  app/Http/Controllers/API/v1/Quiz/QuestionController.php
Labels: Approved by John Harvey, Karlo is Reviewing

#80 E_CLASSROOM-328 [FE/BE] Delete for Quizzes and Admin Table
  app/Http/Controllers/API/v1/Admin/AdminController.php
  app/Http/Controllers/API/v1/Quiz/QuizController.php
  routes/api.php
Labels: Approved by John Harvey, Approved by Karlo

#81 E_CLASSROOM-333 [FE/BE] Apply reusable components to /learnings
  app/Http/Controllers/API/v1/Learn/LearningsController.php
Labels: Approved by John Harvey, Approved by Karlo

#82 [Hotfix] Remove profile picture upload route
  routes/api.php
Labels: Approved by Mary Therese, Approved by John Harvey

#79 E_CLASSROOM-337 [FE/BE] Fix change category in add/edit question
  app/Http/Controllers/API/v1/Quiz/QuestionController.php
Labels: Approved by John Harvey, Approved by Karlo

#77 E_CLASSROOM-324 [FE/BE] Display related subcategories and quizzes for the selected category
  app/Http/Controllers/API/v1/Quiz/QuizController.php
  routes/api.php
Labels: Approved by John Harvey, Approved by Karlo

#83 E_CLASSROOM-329 [FE/BE] Category Delete Function
  app/Http/Controllers/API/v1/Category/CategoryController.php
  routes/api.php
Labels: Approved by John Harvey, Karlo is Reviewing

#85 E_CLASSROOM-343 [Bugfix] User can input admin email in student forget password
  app/Http/Controllers/API/v1/Auth/ForgotPasswordController.php
Labels: Approved by John Harvey, Approved by Karlo

#86 E_CLASSROOM-348 [Bugfix] Quiz title in /categories is not truncated
  app/Http/Controllers/API/v1/User/UserRecentQuizzesController.php
Labels: Approved by John Harvey, Karlo is Reviewing

#87 E_CLASSROOM-365 [Bugfix] Space for card is present even though there is no content
  app/Http/Controllers/API/v1/Quiz/QuizController.php
  routes/api.php
Labels: Approved by Paul Erick, Karlo is Reviewing

#88 E_CLASSROOM-367 [Bugfix] Update character limit for student/admin creation and update
  app/Http/Requests/Admin/StoreAdminRequest.php
  app/Http/Requests/Auth/ChangeNameEmailRequest.php
  app/Http/Requests/Auth/RegisterRequest.php
Labels: Approved by Mary Therese, Karlo is Reviewing

#90 E_CLASSROOM-342 [FE/BE] Implement Change Password for Student Profile
  app/Http/Controllers/API/v1/Student/StudentController.php
  routes/api.php
Labels: Approved by John Harvey, Karlo is Reviewing

#92 E_CLASSROOM-384 [Improvement][Student] Implement sort in /learnings t…
  app/Http/Controllers/API/v1/Learn/LearningsController.php
  app/Traits/LearningsSort.php
Labels: Approved by John Harvey, Karlo is Reviewing

#93 E_CLASSROOM-380 [Improvement][Admin] Edit quiz name and UI fix
  app/Http/Controllers/API/v1/Quiz/QuestionController.php
Labels: Approved by John Harvey, Karlo is Reviewing
